//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/InputManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputManager: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputManager"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""b7bde583-48d5-4afe-8cd2-ebc560ec3fd4"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""6f576589-39f0-4398-b06a-fc3f3757304b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""e77e3bf4-3e1e-4702-902d-1914bf17ec9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c7e17757-87ae-414d-8d57-73bc32d59660"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cadc5d4-e202-4bb0-b303-8190250f538b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerBlue"",
            ""id"": ""dfa8e17e-5725-47b1-9b03-a523ffb77612"",
            ""actions"": [
                {
                    ""name"": ""Joystick"",
                    ""type"": ""Value"",
                    ""id"": ""4c993a1d-e68d-4b4b-9502-709e38b19f48"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn1"",
                    ""type"": ""Button"",
                    ""id"": ""2ad68c57-6c30-4907-8c72-dabbb9bad703"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""26005ae0-dca5-4e1e-9c80-deb842d185f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Arrows"",
                    ""id"": ""751605f9-78f7-49f8-a395-af364ae46c73"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""be9e8fea-4365-482e-b47f-f961567c9604"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9f8d2756-9e10-42c3-ba86-29c086302895"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a9730f2d-f250-48ca-83ae-86771677f2d1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c9680fe4-1b35-45da-9ce6-bbce1705f626"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e8f18757-d333-42e5-aac2-606952dd0f0d"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Btn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b73820e-60f3-42b8-939e-7917d4997cff"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerPink"",
            ""id"": ""03fad348-1a54-4f01-b338-66a786e3277c"",
            ""actions"": [
                {
                    ""name"": ""Joystick"",
                    ""type"": ""Value"",
                    ""id"": ""0bd901e0-32f2-40ed-abf2-28aab2a3f8ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn1"",
                    ""type"": ""Button"",
                    ""id"": ""2a05b31a-015d-4087-aaad-13caabf62883"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""fc880602-b0a0-4e13-9631-85de802e7135"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""521c0734-cc72-4b2c-9044-969bd909b159"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Btn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""dd049188-b9f0-4091-99ef-d1d00b3b79f0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7b122956-2895-472c-891f-6fe6c5a4ac2a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9180818e-bf69-40a9-90dd-acf0ea3e15e1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fde91c63-c92d-40cb-8861-ed8365469db1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9656724d-69e2-4ff3-a3a0-22678634354f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f029f007-20dd-46d1-b65f-236dc1b3a9cc"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerYellow"",
            ""id"": ""07868307-652a-4b8d-a28c-42db61e0ef7b"",
            ""actions"": [
                {
                    ""name"": ""Joystick"",
                    ""type"": ""Value"",
                    ""id"": ""4d9cecaf-a464-4318-a327-6e8334c776eb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn1"",
                    ""type"": ""Button"",
                    ""id"": ""1a0a42c3-86b1-4759-94b2-48556d88516b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""fd9af98d-ff38-4355-bf60-37876aaaaafd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4fa01021-ea7b-409c-92f0-dde34f4924a4"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Btn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""TFGH"",
                    ""id"": ""7dce616b-cd80-4e6f-88db-d42b8a3dd3bf"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""812794c4-e027-4bad-acbd-9c6706d4eefd"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""625a5b6c-8104-422f-a5d4-2f3d7dcff9de"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cc434e49-2758-47b5-bc7b-78e9906c3f72"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b961f6c5-7778-49d7-9f7d-69f9613fdcd8"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0a45f206-752e-4411-be37-02ad4c99397c"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerGreen"",
            ""id"": ""7df3d3d4-4b60-441f-b99c-fd3c353ebc7e"",
            ""actions"": [
                {
                    ""name"": ""Joystick"",
                    ""type"": ""Value"",
                    ""id"": ""63863df3-e088-4385-af57-38fa5f1dd0a4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn1"",
                    ""type"": ""Button"",
                    ""id"": ""404e5120-f805-4df9-b47b-32d028709d94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""6198369e-ba35-47cc-b2c5-57cc8c40a1df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09247d44-463d-4bf2-b151-4476db97266d"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Btn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""IJKL"",
                    ""id"": ""2e96bdfe-448c-4a13-a6e0-d792aae41c9b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""78df3cc6-14dd-4960-8c64-6e033730bc22"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e419a317-b6c2-4c3e-946d-ffc8e0abfafd"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""01ebb9d6-cb46-476f-9021-93e28900107d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""de7e1002-e30a-43c8-8f67-dc38510bd236"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKeyboard"",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""baf983c3-a04b-4e06-a22d-35029e6b327c"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MouseKeyboard"",
            ""bindingGroup"": ""MouseKeyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_Select = m_Game.FindAction("Select", throwIfNotFound: true);
        m_Game_Exit = m_Game.FindAction("Exit", throwIfNotFound: true);
        // PlayerBlue
        m_PlayerBlue = asset.FindActionMap("PlayerBlue", throwIfNotFound: true);
        m_PlayerBlue_Joystick = m_PlayerBlue.FindAction("Joystick", throwIfNotFound: true);
        m_PlayerBlue_Btn1 = m_PlayerBlue.FindAction("Btn1", throwIfNotFound: true);
        m_PlayerBlue_Select = m_PlayerBlue.FindAction("Select", throwIfNotFound: true);
        // PlayerPink
        m_PlayerPink = asset.FindActionMap("PlayerPink", throwIfNotFound: true);
        m_PlayerPink_Joystick = m_PlayerPink.FindAction("Joystick", throwIfNotFound: true);
        m_PlayerPink_Btn1 = m_PlayerPink.FindAction("Btn1", throwIfNotFound: true);
        m_PlayerPink_Select = m_PlayerPink.FindAction("Select", throwIfNotFound: true);
        // PlayerYellow
        m_PlayerYellow = asset.FindActionMap("PlayerYellow", throwIfNotFound: true);
        m_PlayerYellow_Joystick = m_PlayerYellow.FindAction("Joystick", throwIfNotFound: true);
        m_PlayerYellow_Btn1 = m_PlayerYellow.FindAction("Btn1", throwIfNotFound: true);
        m_PlayerYellow_Select = m_PlayerYellow.FindAction("Select", throwIfNotFound: true);
        // PlayerGreen
        m_PlayerGreen = asset.FindActionMap("PlayerGreen", throwIfNotFound: true);
        m_PlayerGreen_Joystick = m_PlayerGreen.FindAction("Joystick", throwIfNotFound: true);
        m_PlayerGreen_Btn1 = m_PlayerGreen.FindAction("Btn1", throwIfNotFound: true);
        m_PlayerGreen_Select = m_PlayerGreen.FindAction("Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_Select;
    private readonly InputAction m_Game_Exit;
    public struct GameActions
    {
        private @InputManager m_Wrapper;
        public GameActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Game_Select;
        public InputAction @Exit => m_Wrapper.m_Game_Exit;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);

    // PlayerBlue
    private readonly InputActionMap m_PlayerBlue;
    private List<IPlayerBlueActions> m_PlayerBlueActionsCallbackInterfaces = new List<IPlayerBlueActions>();
    private readonly InputAction m_PlayerBlue_Joystick;
    private readonly InputAction m_PlayerBlue_Btn1;
    private readonly InputAction m_PlayerBlue_Select;
    public struct PlayerBlueActions
    {
        private @InputManager m_Wrapper;
        public PlayerBlueActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Joystick => m_Wrapper.m_PlayerBlue_Joystick;
        public InputAction @Btn1 => m_Wrapper.m_PlayerBlue_Btn1;
        public InputAction @Select => m_Wrapper.m_PlayerBlue_Select;
        public InputActionMap Get() { return m_Wrapper.m_PlayerBlue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerBlueActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerBlueActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerBlueActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerBlueActionsCallbackInterfaces.Add(instance);
            @Joystick.started += instance.OnJoystick;
            @Joystick.performed += instance.OnJoystick;
            @Joystick.canceled += instance.OnJoystick;
            @Btn1.started += instance.OnBtn1;
            @Btn1.performed += instance.OnBtn1;
            @Btn1.canceled += instance.OnBtn1;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IPlayerBlueActions instance)
        {
            @Joystick.started -= instance.OnJoystick;
            @Joystick.performed -= instance.OnJoystick;
            @Joystick.canceled -= instance.OnJoystick;
            @Btn1.started -= instance.OnBtn1;
            @Btn1.performed -= instance.OnBtn1;
            @Btn1.canceled -= instance.OnBtn1;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IPlayerBlueActions instance)
        {
            if (m_Wrapper.m_PlayerBlueActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerBlueActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerBlueActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerBlueActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerBlueActions @PlayerBlue => new PlayerBlueActions(this);

    // PlayerPink
    private readonly InputActionMap m_PlayerPink;
    private List<IPlayerPinkActions> m_PlayerPinkActionsCallbackInterfaces = new List<IPlayerPinkActions>();
    private readonly InputAction m_PlayerPink_Joystick;
    private readonly InputAction m_PlayerPink_Btn1;
    private readonly InputAction m_PlayerPink_Select;
    public struct PlayerPinkActions
    {
        private @InputManager m_Wrapper;
        public PlayerPinkActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Joystick => m_Wrapper.m_PlayerPink_Joystick;
        public InputAction @Btn1 => m_Wrapper.m_PlayerPink_Btn1;
        public InputAction @Select => m_Wrapper.m_PlayerPink_Select;
        public InputActionMap Get() { return m_Wrapper.m_PlayerPink; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerPinkActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerPinkActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerPinkActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerPinkActionsCallbackInterfaces.Add(instance);
            @Joystick.started += instance.OnJoystick;
            @Joystick.performed += instance.OnJoystick;
            @Joystick.canceled += instance.OnJoystick;
            @Btn1.started += instance.OnBtn1;
            @Btn1.performed += instance.OnBtn1;
            @Btn1.canceled += instance.OnBtn1;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IPlayerPinkActions instance)
        {
            @Joystick.started -= instance.OnJoystick;
            @Joystick.performed -= instance.OnJoystick;
            @Joystick.canceled -= instance.OnJoystick;
            @Btn1.started -= instance.OnBtn1;
            @Btn1.performed -= instance.OnBtn1;
            @Btn1.canceled -= instance.OnBtn1;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IPlayerPinkActions instance)
        {
            if (m_Wrapper.m_PlayerPinkActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerPinkActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerPinkActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerPinkActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerPinkActions @PlayerPink => new PlayerPinkActions(this);

    // PlayerYellow
    private readonly InputActionMap m_PlayerYellow;
    private List<IPlayerYellowActions> m_PlayerYellowActionsCallbackInterfaces = new List<IPlayerYellowActions>();
    private readonly InputAction m_PlayerYellow_Joystick;
    private readonly InputAction m_PlayerYellow_Btn1;
    private readonly InputAction m_PlayerYellow_Select;
    public struct PlayerYellowActions
    {
        private @InputManager m_Wrapper;
        public PlayerYellowActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Joystick => m_Wrapper.m_PlayerYellow_Joystick;
        public InputAction @Btn1 => m_Wrapper.m_PlayerYellow_Btn1;
        public InputAction @Select => m_Wrapper.m_PlayerYellow_Select;
        public InputActionMap Get() { return m_Wrapper.m_PlayerYellow; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerYellowActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerYellowActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerYellowActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerYellowActionsCallbackInterfaces.Add(instance);
            @Joystick.started += instance.OnJoystick;
            @Joystick.performed += instance.OnJoystick;
            @Joystick.canceled += instance.OnJoystick;
            @Btn1.started += instance.OnBtn1;
            @Btn1.performed += instance.OnBtn1;
            @Btn1.canceled += instance.OnBtn1;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IPlayerYellowActions instance)
        {
            @Joystick.started -= instance.OnJoystick;
            @Joystick.performed -= instance.OnJoystick;
            @Joystick.canceled -= instance.OnJoystick;
            @Btn1.started -= instance.OnBtn1;
            @Btn1.performed -= instance.OnBtn1;
            @Btn1.canceled -= instance.OnBtn1;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IPlayerYellowActions instance)
        {
            if (m_Wrapper.m_PlayerYellowActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerYellowActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerYellowActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerYellowActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerYellowActions @PlayerYellow => new PlayerYellowActions(this);

    // PlayerGreen
    private readonly InputActionMap m_PlayerGreen;
    private List<IPlayerGreenActions> m_PlayerGreenActionsCallbackInterfaces = new List<IPlayerGreenActions>();
    private readonly InputAction m_PlayerGreen_Joystick;
    private readonly InputAction m_PlayerGreen_Btn1;
    private readonly InputAction m_PlayerGreen_Select;
    public struct PlayerGreenActions
    {
        private @InputManager m_Wrapper;
        public PlayerGreenActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Joystick => m_Wrapper.m_PlayerGreen_Joystick;
        public InputAction @Btn1 => m_Wrapper.m_PlayerGreen_Btn1;
        public InputAction @Select => m_Wrapper.m_PlayerGreen_Select;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGreenActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerGreenActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerGreenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerGreenActionsCallbackInterfaces.Add(instance);
            @Joystick.started += instance.OnJoystick;
            @Joystick.performed += instance.OnJoystick;
            @Joystick.canceled += instance.OnJoystick;
            @Btn1.started += instance.OnBtn1;
            @Btn1.performed += instance.OnBtn1;
            @Btn1.canceled += instance.OnBtn1;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IPlayerGreenActions instance)
        {
            @Joystick.started -= instance.OnJoystick;
            @Joystick.performed -= instance.OnJoystick;
            @Joystick.canceled -= instance.OnJoystick;
            @Btn1.started -= instance.OnBtn1;
            @Btn1.performed -= instance.OnBtn1;
            @Btn1.canceled -= instance.OnBtn1;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IPlayerGreenActions instance)
        {
            if (m_Wrapper.m_PlayerGreenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerGreenActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerGreenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerGreenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerGreenActions @PlayerGreen => new PlayerGreenActions(this);
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("MouseKeyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IGameActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
    public interface IPlayerBlueActions
    {
        void OnJoystick(InputAction.CallbackContext context);
        void OnBtn1(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IPlayerPinkActions
    {
        void OnJoystick(InputAction.CallbackContext context);
        void OnBtn1(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IPlayerYellowActions
    {
        void OnJoystick(InputAction.CallbackContext context);
        void OnBtn1(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IPlayerGreenActions
    {
        void OnJoystick(InputAction.CallbackContext context);
        void OnBtn1(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
}
